config/routes.rb
Rails.application.routes.draw do

  resources :comments, only: [:index, :create] do
    resources :votes, only: :create
  end

  root 'comments#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_many :votes
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :comment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comment = Comment.new

    if params[:q].present?
      @comments = Comment.where('content like ?', "%#{params[:q]}%")
    else
      @comments = Comment.all
    end
  end

  def create
    @comment = Comment.create(comment_params)
    # render json: @comment.as_json
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @comment = Comment.find(params[:comment_id])
    Vote.create!(comment: @comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/_comment.html.erb
<div id="comment-<%= comment.id %>">
  <%= comment.content %>
  <small id="votes-comment-<%= comment.id %>"> 
    <%= link_to comment.votes.count, comment_votes_path(comment), method: :post, remote: :true %>
  </small>
</div>

app/views/comments/create.js.erb
$("#comments").append("<h4> <%= @comment.content %> </h4>");

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

<iframe width="560" height="315" src="https://www.youtube.com/embed/wNCi-vfgu9g" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

<%= form_with model: @comment do |f| %>
  <%= f.label :content, "Ingresa comentario" %>
  <%= f.text_field :content %>
  <%= f.submit :enviar %>
<% end %>

<!-- Formulario de búsqueda -->
<form action="<%= comments_path %>">
  <label for="">Buscador:</label>
  <input type="text" name="q">
</form>

<div id="comments">
  <table>
    <tbody>
      <%= render @comments %>
    </tbody>
  </table>
</div>

<script>
  $("[name=q]").keyup(function(event) {
    $.ajax({
      url: '<%= comments_path %>',
      type: 'GET',
      dataType: 'script',
      data: { q: $(this).val()}
    })
    .done(function() {
      console.log("success");
    })
    .fail(function() {
      console.log("error");
    })
    .always(function() {
      console.log("complete");
    });
   });
</script>

app/views/comments/index.js.erb
$("#comments").html("<%= j render @comments %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Semana2501</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/votes/create.js.erb
// var value = $("#votes-comment-<%= @comment.id %>").text();
// $("#votes-comment-<%= @comment.id %>").text(parseInt(value) + 1);

 $("#comment-<%= @comment.id %>").html("<%= j render @comment %>")